# Generated by Django 6.0.3 on 2026-10-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Unidades disponibles en almacén'),
        ),
    ]
